import type { NextPage } from "next";
import Head from "next/head";
import MobileNav from "components/sections/header/mobileNav/mobileNav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Invoice Dapp | Create an Invoice on the Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileNav />
      <main>
        <h1>Body</h1>
      </main>
    </>
  );
};

export default Home;
