import type { NextPage } from "next";
import Head from "next/head";
import AppTemplate from "components/templates/appTemplate/appTemplate";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Invoice Dapp | Create an Invoice on the Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppTemplate />
    </>
  );
};

export default Home;
